name: Deploy to Chrome Web Store

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      - name: Build extension
        run: npm run build

      - name: Create release ZIP
        run: |
          cd dist
          zip -r ../vega-extension-${{ github.ref_name }}.zip .
          cd ..

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: vega-extension-${{ github.ref_name }}.zip
          extension-id: oboedhpojbjemdmojfchifppbgbfehol
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vega-extension-${{ github.ref_name }}.zip
          generate_release_notes: true
          body: |
            ## 🎉 New Release Available!

            This version has been automatically deployed to the Chrome Web Store.

            ### 📥 Installation

            **Chrome Web Store**: [Install Vega AI Job Capture Extension](https://chromewebstore.google.com/detail/vega-ai-job-capture/oboedhpojbjemdmojfchifppbgbfehol)

            ### 📋 What's Changed

            See the auto-generated release notes below for a complete list of changes.

            ---

  version-bump:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.release_type }} -m "Release %s"
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update manifest version
        run: |
          node -e "
          const fs = require('fs');
          const manifest = JSON.parse(fs.readFileSync('./src/manifest.json'));
          manifest.version = '${{ env.VERSION }}';
          fs.writeFileSync('./src/manifest.json', JSON.stringify(manifest, null, 2) + '\n');
          "
          git add src/manifest.json
          git commit --amend --no-edit

      - name: Push changes
        run: |
          git push
          git push --tags
