name: Update Coverage Badge

on:
  push:
    branches: [ master ]

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - run: npm ci
    
    - run: npm run test:coverage
    
    - name: Update coverage badge
      run: |
        COVERAGE=$(node -e "const c = require('./coverage/coverage-summary.json'); console.log(c.total.lines.pct.toFixed(2))")
        
        # Determine color based on coverage
        if (( $(echo "$COVERAGE >= 90" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$COVERAGE >= 80" | bc -l) )); then
          COLOR="green"
        elif (( $(echo "$COVERAGE >= 70" | bc -l) )); then
          COLOR="yellow"
        elif (( $(echo "$COVERAGE >= 60" | bc -l) )); then
          COLOR="orange"
        else
          COLOR="red"
        fi
        
        # Update both coverage percentage and color
        sed -i -E "s/Coverage-[0-9.]*%25-[a-z]+/Coverage-${COVERAGE}%25-${COLOR}/" README.md
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet || (git add README.md && git commit -m "Update coverage to ${COVERAGE}%" && git push)